# Generated by Django 3.0.4 on 2020-03-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=15, unique=True)),
                ('tiles', models.PositiveIntegerField()),
                ('outcome', models.IntegerField(choices=[(1, 'Xwin'), (2, 'Owin'), (-1, 'Draw'), (0, 'Nd')], default=0)),
                ('turn', models.IntegerField(choices=[(0, 'X'), (1, 'O')], default=1)),
                ('start_DT', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField(choices=[(0, 'X'), (1, 'O')])),
                ('move', models.PositiveIntegerField()),
                ('time', models.TimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameserver.Game')),
            ],
        ),
    ]
